ALTER TABLE `identities` ADD `address_shown` VARCHAR( 64 ) NOT NULL AFTER `address`;
ALTER TABLE `identities` ADD `photo` VARCHAR( 64 ) NOT NULL AFTER `lastname` ;
ALTER TABLE `identities` ADD `about` TEXT NOT NULL AFTER `photo` ;
ALTER TABLE `services` ADD `icon` VARCHAR( 32 ) NOT NULL AFTER `service_type_id` , ADD `has_feed` TINYINT( 1 ) NOT NULL AFTER `icon` , ADD `is_contact` TINYINT( 1 ) NOT NULL AFTER `has_feed` ;
ALTER TABLE `services` ADD INDEX ( `has_feed` );  
ALTER TABLE `services` ADD INDEX ( `is_contact` );
UPDATE `services` SET has_feed=1;
ALTER TABLE `services` ADD `help` VARCHAR( 255 ) NOT NULL AFTER `service_type_id` ;
UPDATE `services` SET `icon` = 'flickr.gif' WHERE `services`.`id`=1;
UPDATE `services` SET `icon` = 'delicious.gif' WHERE `services`.`id` =2;
UPDATE `services` SET `icon` = 'ipernity.gif' WHERE `services`.`id` =3;
UPDATE `services` SET `icon` = '23hq.gif' WHERE `services`.`id` =4;
UPDATE `services` SET `icon` = 'twitter.gif' WHERE `services`.`id` =5;
UPDATE `services` SET `icon` = 'pownce.gif' WHERE `services`.`id` =6;
UPDATE `services` SET `icon` = 'vimeo.gif' WHERE `services`.`id` =10;
UPDATE `services` SET `icon` = 'rss.gif' WHERE `services`.`id` =8;
UPDATE `services` SET `icon` = 'upcoming.gif' WHERE `services`.`id` =9;
UPDATE `services` SET `icon` = 'lastfm.gif' WHERE `services`.`id` =11;
UPDATE `services` SET `icon` = 'qype.gif' WHERE `services`.`id` =12;
UPDATE `services` SET `icon` = 'magnolia.gif' WHERE `services`.`id` =13;
UPDATE `services` SET `icon` = 'stumbleupon.gif' WHERE `services`.`id` =14;
UPDATE `services` SET `icon` = 'corkd.gif' WHERE `services`.`id` =15;
UPDATE `services` SET `icon` = 'dailymotion.gif' WHERE `services`.`id` =16;
UPDATE `services` SET `icon` = 'zooomr.gif' WHERE `services`.`id` =17;
UPDATE `services` SET `icon` = 'odeo.gif' WHERE `services`.`id` =18;
UPDATE `services` SET `icon` = 'ilike.gif' WHERE `services`.`id` =19;
UPDATE `services` SET `icon` = 'wevent.gif' WHERE `services`.`id` =20;
UPDATE `services` SET `icon` = 'imthere.gif' WHERE `services`.`id` =21;
UPDATE `services` SET `icon` = 'newsvine.gif' WHERE `services`.`id` =22;
INSERT INTO `services` (`id` ,`name` ,`url` ,`service_type_id` ,`help` ,`icon` ,`has_feed` ,`is_contact` ,`created` ,`modified`) VALUES (23 , 'Jabber', 'http://jabber.org/', '5', '', 'jabber.gif', '0', '1', NOW(), NOW()), (24 , 'GTalk', 'http://www.google.com/talk/', '5', '', 'gtalk.gif', '0', '1', NOW(), NOW()), ('25', 'ICQ', 'htp://icq.com/', '5', '', 'icq.gif', '0', '1', NOW() , NOW()), ('26', 'YIM', 'http://messenger.yahoo.com/', '5', '', 'yim.gif', '0', '1', NOW(), NOW());
INSERT INTO `services` (`id`,`name`,`url`,`service_type_id`,`help`,`icon`,`has_feed`,`is_contact`,`created`,`modified`) VALUES ('27', 'AIM', 'http://aim.com/', '5', '', 'aim.gif', '0', '1', NOW(), NOW()), ('28', 'Skype', 'http://skype.com/', '5', '', 'skype.gif', '0', '1', NOW(), NOW()), ('29', 'MSN', 'http://im.live.com/', '5', '', 'msn.gif', '0', '1', NOW() , NOW()), ('30', 'Facebook', 'http://facebook.com/', '5', 'Please enter your profile number. You see that in the URL, when you go to your own Facebook profile page.', 'facebook.gif', '0', '0', NOW() , NOW());
INSERT INTO `services` (`id`,`name`,`url`,`service_type_id`,`help`,`icon`,`has_feed`,`is_contact`,`created`,`modified`) VALUES ('31', 'Second Life', 'http://secondlife.com/', '5', '', 'sl.gif', '0', '0', NOW(), NOW()), ('32', 'LinkedIn', 'http://linkedin.com/', '5', '', 'linkedin.gif', '0', '0', NOW(), NOW()), ('33', 'Xing', 'http://xing.com/', '5', '', 'xing.gif', '0', '0', NOW() , NOW());