UPDATE `services` SET `name` = 'Flickr' WHERE `id` =1 LIMIT 1 ;
ALTER TABLE `services` CHANGE `help` `help` TEXT CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL;
UPDATE `services` SET `help` = 'Please enter your profile number. You see that in the URL, when you go to your own Upcoming profile page.<br />Example: User »<strong>dotdean</strong>« has the URL »http://upcoming.yahoo.com/user/<strong>89735</strong>/« and the iD »<strong>89735</strong>« ' WHERE `id` =9 LIMIT 1 ;
UPDATE `services` SET `help` = 'Please enter your User-ID. You see that in the URL, when you go to your own Scribd profile page.<br />Example: User »<strong>poolie</strong>« has the URL »http://www.scribd.com/people/view/<strong>122488-poolie</strong>/« and the iD »<strong>122488-poolie</strong>« ' WHERE `id` =36 LIMIT 1 ;
UPDATE `services` SET `help` = 'Please enter your ICQ Number.<br />Example: <strong>123456789</strong> ' WHERE `id` =25 LIMIT 1 ;
UPDATE `services` SET `help` = 'Please enter your Jabber-ID.<br />Example: <strong>username@jabberserver.org</strong> ' WHERE `id` =23 LIMIT 1 ;
UPDATE `services` SET `help` = 'Please enter your Skype-Name. ' WHERE `id` =28 LIMIT 1 ;
UPDATE `services` SET `help` = 'Please enter your GTalk-Username.<br />Example: <strong>username@gmail.com</strong> ' WHERE `id` =24 LIMIT 1 ;
UPDATE `services` SET `help` = 'Please enter your Yahoo! Messenger Nickname. ' WHERE `id` =26 LIMIT 1 ;
UPDATE `services` SET `help` = 'Please enter your AIM Nickname. ' WHERE `id` =27 LIMIT 1 ;
UPDATE `services` SET `help` = 'Please enter your Xing-ID. You see that in the URL, when you go to your own Xing profile page.<br />Example: User »<strong>Alexander Kaiser</strong>« has the URL »https://www.xing.com/profile/<strong>Alexander_Kaiser5</strong>/« and the ID »<strong>Alexander_Kaiser5</strong>« ' WHERE `id` =33 LIMIT 1 ;
UPDATE `services` SET `help` = 'Please enter your LinkedIn-ID. You see that in the URL of your own public profile.<br />Example: User »<strong>Alexander Kaiser</strong>« has the URL »http://www.linkedin.com/in/<strong>poolie</strong>/« and the iD »<strong>poolie</strong>« ' WHERE `id` =32 LIMIT 1 ;
UPDATE `services` SET `help` = 'Please enter your SlideShare Nickname. ' WHERE `id` =34 LIMIT 1 ;
UPDATE `services` SET `help` = 'Please enter your Plazes Nickname. ' WHERE `id` =35 LIMIT 1 ;
UPDATE `services` SET `help` = 'Please enter your MoodMill Nickname. ' WHERE `id` =37 LIMIT 1 ;
UPDATE `services` SET `help` = 'Please enter your Digg.com Nickname. ' WHERE `id` =38 LIMIT 1 ;
UPDATE `services` SET `help` = 'Please enter your AIM Nickname. ' WHERE `id` =27 LIMIT 1 ;
UPDATE `services` SET `help` = 'Please enter your Flickr screen name. You see that in the URL, when you go to your own photos page.<br />Example: User »<strong>poolie</strong>« has the URL »http://www.flickr.com/photos/<strong>poolie</strong>/« and the screen name »<strong>poolie</strong>« ' WHERE `id` =1 LIMIT 1 ;
UPDATE `services` SET `help` = 'Please enter your del.icio.us Username. ' WHERE `id` =2 LIMIT 1 ;
UPDATE `services` SET `help` = 'Please enter your Ipernity Username. ' WHERE `id` =3 LIMIT 1 ;
UPDATE `services` SET `help` = 'Please enter your 23hq Username. ' WHERE `id` =4 LIMIT 1 ;
UPDATE `services` SET `help` = 'Please enter your Twitter Username. ' WHERE `id` =5 LIMIT 1 ;
UPDATE `services` SET `help` = 'Please enter your Pownce Username. ' WHERE `id` =6 LIMIT 1 ;
UPDATE `services` SET `help` = 'Please enter your Vimeo Username. ' WHERE `id` =10 LIMIT 1 ;
UPDATE `services` SET `help` = 'Please enter your Last.fm Username. ' WHERE `id` =11 LIMIT 1 ;
UPDATE `services` SET `help` = 'Please enter your Qype Username. ' WHERE `id` =12 LIMIT 1 ;
UPDATE `services` SET `help` = 'Please enter your Ma.gnolia Username. ' WHERE `id` =13 LIMIT 1 ;
UPDATE `services` SET `help` = 'Please enter your StumbleUpon Username. ' WHERE `id` =14 LIMIT 1 ;
UPDATE `services` SET `help` = 'Please enter your Corkd Username. ' WHERE `id` =15 LIMIT 1 ;
UPDATE `services` SET `help` = 'Please enter your Dailymotion Username. ' WHERE `id` =16 LIMIT 1 ;
UPDATE `services` SET `help` = 'Please enter your Zooomr Username. ' WHERE `id` =17 LIMIT 1 ;
UPDATE `services` SET `help` = 'Please enter your Odeo Username. ' WHERE `id` =18 LIMIT 1 ;
UPDATE `services` SET `help` = 'Please enter your iLike Username. ' WHERE `id` =19 LIMIT 1 ;
UPDATE `services` SET `help` = 'Please enter your wevent Username. ' WHERE `id` =20 LIMIT 1 ;
UPDATE `services` SET `help` = 'Please enter your ImThere Username. ' WHERE `id` =21 LIMIT 1 ;
UPDATE `services` SET `help` = 'Please enter your Newsvine Username. ' WHERE `id` =22 LIMIT 1 ;
