ALTER TABLE `access_tokens` CONVERT TO CHARACTER SET utf8;
ALTER TABLE `consumers` CONVERT TO CHARACTER SET utf8;
ALTER TABLE `locations` CONVERT TO CHARACTER SET utf8;
ALTER TABLE `nonces` CONVERT TO CHARACTER SET utf8;
ALTER TABLE `request_tokens` CONVERT TO CHARACTER SET utf8;